version: "3"
services:
  alpine-magento-cli:
    build:
      context: .
    image: augustash/alpine-magento-cli
    labels:
      - "com.augustash.description=August Ash Alpine Magento CLI Image"
      - "com.augustash.development-only"
    ulimits:
      nproc: 65535
      nofile:
        soft: 64000
        hard: 64000
    depends_on:
      - mysql
    volumes:
      - ~/.composer:/.composer
    env_file: magento.env
    environment:
      - MAGENTO_VERSION=2.2.2
      - MAGENTO_INSTALL_DB=true
      - MAGENTO_USE_SAMPLE_DATA=true
      - MAGENTO_BASE_URL=http://magento.dev/

  mysql:
    image: percona:5.7
    env_file: database.env
